import Head from "next/head";
import React from "react";
import Layout from "../../shared/components/Layout";
import VideoContainer from '../../features/Video/VideoContainer/VideoContainer'

function QarabaghPage() {
  return (
    <Layout>
      <Head>
        <title>adgozalli | Video</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VideoContainer />
    </Layout>
  );
}

export default QarabaghPage;
