import Head from "next/head";
import React from "react";
import Layout from "../../shared/components/Layout";
import QarabagContainer from '../../features/Qarabag/QarabagContainer/QarabaghContainer'

function QarabaghPage() {
  return (
    <Layout>
      <Head>
        <title>adgozalli | Qarabag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QarabagContainer />
    </Layout>
  );
}

export default QarabaghPage;
