import Head from "next/head";
import React from "react";
import Layout from "../../shared/components/Layout";
import PhotoContainer from '../../features/Photo/PhotoContainer/PhotoContainer'

function QarabaghPage() {
  return (
    <Layout>
      <Head>
        <title>adgozalli | Photo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PhotoContainer />
    </Layout>
  );
}

export default QarabaghPage;
