import Head from "next/head";
import React from "react";
import BioContainer from "../../features/Bio/BioContainer/BioContainer";
import Layout from "../../shared/components/Layout";

function BioPage() {
  return (
    <Layout>
      <Head>
        <title>adgozalli | Bio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BioContainer />
    </Layout>
  );
}

export default BioPage;
