import Head from "next/head";
import styles from "../styles/Home.module.css";
import Layout from "../shared/components/Layout";
import HomeContainer from "../features/Home/HomeContainer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Layout>
        <Head>
          <title>adgozalli | Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HomeContainer />
      </Layout>

      {/* <main className={styles.main}>
        <Header />
        <SwipbleMenu />
      </main> */}
    </div>
  );
}
